### ISSUE TITLE
Initial todo

### ISSUE THREAD

**Issue by gassmoeller** [gassmoeller/BSSC#1]
* [x] Set up repository
 * [x] Create Readme.md
 * [x] Create github pages
 * [x] Create Contributing.md
 * [ ] Create Style guide
 * [x] Make repo public
 * [x] Create Code of Conduct
 * [ ] Develop first guides as preliminary one page guides (to have showcases)
 * [ ] Announce existence on BSSw, CIG mailing lists and potentially others
 * [x] Develop self assessment questions
 * [ ] Conduct interviews
 * [ ] Incorporate feedback of select interviews
